WebDuLich/WebDuLichDev/Controllers/FileController.cs
using DuLichDLL.BAL;
using DuLichDLL.Model;
using DuLichDLL.TOOLS;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDuLichDev.WebUtility;

namespace WebDuLichDev.Controllers
{
    public class FileController : BaseController
    {

        public ActionResult UploadAvatar(IEnumerable<HttpPostedFileBase> fileUpload)
        {
            //string fileNameGuid = "";
            string fileName = "";
            foreach (var file in fileUpload)
            {
                // Some browsers send file names with full path. We only care about the file name.
                fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                //var fileName = Path.GetFileName(file.FileName);

                var destinationPath = Path.Combine(Server.MapPath("~/Data/Avatar/Place/"), fileName);
                file.SaveAs(destinationPath);
            }
            return Json(new { dataName = fileName }, "text/plain");
        }
        public ActionResult RemoveAvatarPlace(string fileNames)
        {
            ProcessWithFiles processfile = new ProcessWithFiles();
            var destinationPath = Path.Combine(Server.MapPath("~/Data/Avatar/Place/"), fileNames);

            processfile.DeleteFile(destinationPath);

            return Json(new { status = "OK" }, "text/plain");

        }
        private bool IsImage(HttpPostedFileBase file)
        {
            if (file.ContentType.Contains("image"))
            {
                return true;
            }

            string[] formats = new string[] { ".jpg", ".png", "bmp" }; // add more if u like...

            // linq from Henrik Stenbæk
            return formats.Any(item => file.FileName.EndsWith(item, StringComparison.OrdinalIgnoreCase));
        }
        public ActionResult UploadAvatarPlace(IEnumerable<HttpPostedFileBase> fileUpload, int ID)
        {
            //HotelInfo hotelinfo = new HotelInfo();
            DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
            //hotelinfo.dlPlace = dlPlaceBal.GetByID(ID);
            var fileName = "";
            var serserPath = Server.MapPath("~/Data/Avatar/Place/");
            if (System.IO.File.Exists(serserPath + dlPlaceBal.GetByID(ID).Avatar)) //Xóa file có trước nếu đã có trong csdl. Việc up là duy nhất
                System.IO.File.Delete(serserPath + dlPlaceBal.GetByID(ID).Avatar);

            Boolean fileOK = false;

            if (null != fileUpload)
            {
                foreach (var file in fileUpload)
                {
                    fileOK = false;
                    fileOK = IsImage(file);
                    if (false == fileOK)
                        break;
                }
            }
            if (true == fileOK)
            {
                foreach (var file in fileUpload)
                {

                    fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    var destinationPath = Path.Combine(serserPath, fileName);
                    file.SaveAs(destinationPath);
                }
                return Json(new { dataName = fileName }, "text/plain");
            }
            else
            {
                return Json(new { dataName = "Fail: Not allow file have extension that" }, "text/plain");
            }

        }


        public ActionResult UploadImagePlace(IEnumerable<HttpPostedFileBase> fileUpload)
        {
            //var serserPath = Server.MapPath("~/Data/Images/Place/");
            List<string> listfilenameGuid = new List<string>();
            bool fileOK = true;

            if (null != fileUpload)
            {

                foreach (var file in fileUpload)
                {
                    if (false == IsImage(file))
                    {
                        fileOK = false;
                        break;
                    }
                }
            }
            if (true == fileOK)
            {
                foreach (var file in fileUpload)
                {
                    // Some browsers send file names with full path. We only care about the file name.
                    //var fileName = Path.GetFileName(file.FileName);
                    var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    var destinationPath = Path.Combine(Server.MapPath("~/Data/Images/Place/"), fileName);
                    file.SaveAs(destinationPath);
                    listfilenameGuid.Add(fileName);
                }
                return Json(new { dataname = listfilenameGuid }, "text/plain");
            }
            else
            {
                return Json(new { dataname = "Fail: Not allow file have extension that" }, "text/plain");
            }

        }
        public ActionResult RemoveImagePlace(string fileNames)
        {
            ProcessWithFiles processfile = new ProcessWithFiles();
            var destinationPath = Path.Combine(Server.MapPath("~/Data/Images/Place/"), fileNames);

            processfile.DeleteFile(destinationPath);

            return Json(new { status = "OK" }, "text/plain");

        }
        public ActionResult UploadAvatarCity(IEnumerable<HttpPostedFileBase> fileUpload, int cityId)
        {

            DL_City dlCity = new DL_City();
            var serserPath = Server.MapPath("~/Data/Avatar/City/");
            if (System.IO.File.Exists(serserPath + dlCity.Avatar)) //Xóa file có trước nếu đã có trong csdl. Việc up là duy nhất
                System.IO.File.Delete(serserPath + fileUpload);
            var fileName = "";

            bool fileOK = true;

            if (null != fileUpload)
            {
                foreach (var file in fileUpload)
                {
                    fileOK = IsImage(file);
                    if (false == fileOK)
                        break;
                }
            }
            if (true == fileOK)
            {
                foreach (var file in fileUpload)
                {
                    fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    var destinationPath = Path.Combine(serserPath, fileName);
                    file.SaveAs(destinationPath);
                }
                return Json(new { dataName = fileName }, "text/plain");
            }
            else
            {
                return Json(new { dataName = "Fail: Not allow file have extension that" }, "text/plain");
            }
        }
        public ActionResult RemoveAvatarCity(string fileNames)
        {
            ProcessWithFiles processfile = new ProcessWithFiles();
            var destinationPath = Path.Combine(Server.MapPath("~/Data/Avatar/City/"), fileNames);

            processfile.DeleteFile(destinationPath);

            return Json(new { status = "OK" }, "text/plain");

        }


    }
}

WebDuLich/WebDuLichDev/Controllers/HotelController.cs
using DuLichDLL.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebDuLichDev.Models;
using DuLichDLL.BAL;
using DuLichDLL.TOOLS;
using WebDuLichDev.WebUtility;
using System.IO;
using DuLichDLL.ExceptionType;
using WebDuLichDev.Enum;


namespace WebDuLichDev.Controllers
{
    public class HotelController : BaseController
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(HotelController).Name);
        string version = "Version " + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString() + " ";

        private static List<HotelInfo> HotelBookTemp = new List<HotelInfo>();
        //
        // GET: /Hotel/

        public ActionResult Index()
        {
            return View();
        }
        #region admin

        public ActionResult ListHotel()
        {
            try
            {
                vm_Pagination pagination = new vm_Pagination
                {
                    Page = MvcApplication.pageDefault,
                    PageSize = MvcApplication.pageSizeDefault,
                    OrderBy = DL_PlaceColumns.CreatedDate.ToString(),
                    OrderDirection = "DESC",

                };
                long totalRecords = 0;

                DL_PlaceBAL dlPlaceBAL = new DL_PlaceBAL();
                var model = dlPlaceBAL.GetListWithFilter(0, "", "", (long)DL_PlaceTypeId.Hotels, pagination.Page.Value, pagination.PageSize.Value, pagination.OrderBy, pagination.OrderDirection, out totalRecords);

                common.LoadPagingData(this, pagination.Page ?? MvcApplication.pageDefault, pagination.PageSize ?? MvcApplication.pageSizeDefault, totalRecords);
                ViewData["OrderBy"] = pagination.OrderBy;
                ViewData["OrderDirection"] = pagination.OrderDirection;

                return View(model);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }
        }

        [HttpPost]
        public ActionResult ListHotel(vm_Pagination pagination, vm_Search dataSearch)
        {
            try
            {
                long totalRecords = 0;

                DL_PlaceBAL dlPlaceBAL = new DL_PlaceBAL();
                var model = dlPlaceBAL.GetListWithFilter(0, "", "", (long)DL_PlaceTypeId.Hotels, pagination.Page.Value, pagination.PageSize.Value, pagination.OrderBy, pagination.OrderDirection, out totalRecords);

                common.LoadPagingData(this, pagination.Page ?? MvcApplication.pageDefault, pagination.PageSize ?? MvcApplication.pageSizeDefault, totalRecords);
                ViewData["OrderBy"] = pagination.OrderBy;
                ViewData["OrderDirection"] = pagination.OrderDirection;

                return View(model);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }
        }
        public ActionResult AddHotel()
        {
            //ViewBag.NewPlaceID = ID;
            return View();
        }

        [HttpPost]
        public ActionResult AddHotel(HotelInfo hotelinfo, string[] imagePlace)
        {
            try
            {
                bool result = false;
                DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
                List<DL_ImagePlace> listdlImangePlace = new List<DL_ImagePlace>();
                if (null != imagePlace)
                {
                    for (int index = 0; index < imagePlace.Count(); index++)
                    {
                        DL_ImagePlace temp = new DL_ImagePlace();
                        temp.LinkImage = imagePlace[index];
                        listdlImangePlace.Add(temp);
                    }
                }
                hotelinfo.dlPlace.DL_PlaceTypeId = (long)DL_PlaceTypeId.Hotels;
                hotelinfo.listImagePlace = listdlImangePlace;
                hotelinfo.dlPlace.TotalPointRating = 0;
                hotelinfo.dlPlace.TotalUserRating = 0;
                result=dlPlaceBal.InsertHotel(hotelinfo.dlPlace, hotelinfo.dlHotelPlaceInfoDetail, hotelinfo.listImagePlace);
                if (true == result)
                {
                    TempData["Message"] = ResultMessage.SUC_Insert;
                    return RedirectToAction("ListHotel");
                }
                else
                {
                    TempData["Message"] = ResultMessage.ERR_Insert;
                    return RedirectToAction("ListHotel");
                }
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }

        }
        public ActionResult UpdateHotel(long ID)
        {
            try
            {
                HotelInfo hotelinfo = new HotelInfo();
                DL_HotelPlaceInfoDetailBAL hotelInfoBal = new DL_HotelPlaceInfoDetailBAL();
                DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
                DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();
                List<DL_ImagePlace> listdlImangePlace = new List<DL_ImagePlace>();
                hotelinfo.dlHotelPlaceInfoDetail = hotelInfoBal.GetByDLPlaceID(ID);
                hotelinfo.dlPlace = dlPlaceBal.GetByID(ID);
                listdlImangePlace = dlImagePlaceBal.GetByDLPlaceID(ID);
                hotelinfo.listImagePlace = listdlImangePlace;
                var model = hotelinfo;
                return View(model);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }

            
        }
        [HttpPost]
        public ActionResult UpdateHotel(HotelInfo hotelinfo, string[] imagePlace)
        {
            try
            {
                bool result = false;
                DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
                List<DL_ImagePlace> listdlImangePlace = new List<DL_ImagePlace>();
                List<DL_ImagePlace> listdlImangePlaceTemp = new List<DL_ImagePlace>();
                List<DL_ImagePlace> listdlImangePlaceTempNew = new List<DL_ImagePlace>();
                DL_ImagePlaceBAL dlImageBal = new DL_ImagePlaceBAL();
                if (null != imagePlace)
                {
                    for (int index = 0; index < imagePlace.Count(); index++)
                    {
                        DL_ImagePlace temp = new DL_ImagePlace();
                        temp.LinkImage = imagePlace[index];
                        listdlImangePlaceTempNew.Add(temp);
                    }
                }
                //listdlImangePlace = dlImageBal.GetByDLPlaceID(hotelinfo.dlPlace.ID);
                if (hotelinfo.listImagePlace != null)
                {
                    foreach (var i in hotelinfo.listImagePlace)
                    {
                        if (i.Status == 1)
                            dlImageBal.Update(i);
                        else
                        {
                            i.Status = 0;
                            dlImageBal.Update(i);
                        }
                    }
                }
                hotelinfo.dlHotelPlaceInfoDetail.DL_PlaceId = hotelinfo.dlPlace.ID;
                hotelinfo.dlPlace.DL_PlaceTypeId = (long)DL_PlaceTypeId.Hotels;
                result = dlPlaceBal.UpdateHotel(hotelinfo.dlPlace, hotelinfo.dlHotelPlaceInfoDetail, listdlImangePlaceTempNew);
                if (true == result)
                {
                    log.Info("Update Hotel Sucess");
                    TempData["Message"] = ResultMessage.SUC_Update;
                    return RedirectToAction("ListHotel");
                }
                else
                {
                    TempData["Message"] = ResultMessage.ERR_Update;
                    return RedirectToAction("ListHotel");
                }
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }

WebDuLich/WebDuLichDev/Views/City/AddCity.cshtml
@model WebDuLichDev.Models.CityInfo
@{
    ViewBag.Title = "AddCity";
    Layout = "~/Views/Shared/_Layout.cshtml";
   
}

<h2>@Resources.Language.Add @Resources.Language.City</h2>

@using (Html.BeginForm("AddCity", "City", FormMethod.Post, new { @class = "Add_City ", @id = "frmAddCity" }))
{
    <input name="dlCity.ID" value="@Model.dlCity.ID" type="hidden" />
    <div class="control-group" style="width: 50%">
        <label class="control-label" for="input01">@Resources.Language.City</label>
        <div class="controls">
            @Html.TextBoxFor(m => m.dlCity.CityName,new { @readonly = true })
        </div>
    </div>
  
    <div>
        <ul id="panelbar">
            <li class="k-state-active">
                <span class="k-link k-state-selected">@Resources.Language.BasicInfo</span>
                <div>
                    <div class="control-group">
                        <label class="control-label" for="input01">@Resources.Language.Avatar</label>
                        <div class="controls">
                            <input id="uploadAvatar" name="fileUpload" type="file" />
                            <input id="Avatar" name="dlCity.Avatar" value="@Model.dlCity.Avatar" type="hidden" required="" validationmessage="Please upload {0}" />
                            <div id="imgPhotoAvatar">
                                <div class="row">
                                    <div class="span8">
                                        <ul class="thumbnails">
                                            @if (null != Model && Model.dlCity != null)
                                            {      
                                                @:<li class="span2" id="@Model.dlCity.Avatar"><a class=thumbnail><img src="/Data/Avatar/City/@Model.dlCity.Avatar" alt='' /></a></li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="control-group">
                        <label class="control-label" for="input01">@Resources.Language.Introduce</label>
                        <div id="content_city" class="k-content">
                            <textarea id="editor" name="dlCity.Summary" rows="5" cols="20" style="width: 100%; height: 400px">                  
                   @HttpUtility.HtmlDecode(Model.dlCity.Summary);      
                </textarea>
                        </div>
                    </div>
                </div>
            </li>

            <li>
                <span class="">@Resources.Language.DetailInfo</span>
                <div id="tabstrip">
                    <ul>
                        <li class="k-state-active">@Resources.Language.History</li>
                        <li>@Resources.Language.Nature</li>
                        <li>@Resources.Language.Social</li>
                        <li>@Resources.Language.Administrative</li>
                        <li>@Resources.Language.Economy</li>
                        <li>@Resources.Language.Travel</li>
                    </ul>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="History" name="dlCityInfoDetail.History" rows="5" cols="20" style="width: 100%; height: 400px">                  
                   @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.History   )   
                </textarea>
                        </div>
                    </div>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="Nature" name="dlCityInfoDetail.Nature" rows="5" cols="20" style="width: 100%; height: 400px">                  
                    @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.Nature   )  
                </textarea>
                        </div>
                    </div>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="Social" name="dlCityInfoDetail.Social" rows="5" cols="20" style="width: 100%; height: 400px">                  
                   @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.Social )    
                </textarea>
                        </div>
                    </div>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="Administrative" name="dlCityInfoDetail.Administrative" rows="5" cols="20" style="width: 100%; height: 400px">                  
                     @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.Administrative   )   
                </textarea>
                        </div>
                    </div>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="Economy" name="dlCityInfoDetail.Economy" rows="5" cols="20" style="width: 100%; height: 400px">                  
                   @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.Economy)
                </textarea>
                        </div>
                    </div>
                    <div>
                        <div class="k-content">
                            <textarea class="editor" id="Travel" name="dlCityInfoDetail.Travel" rows="5" cols="20" style="width: 100%; height: 400px">                  
                     @HttpUtility.HtmlDecode(Model.dlCityInfoDetail.Travel)      
                </textarea>
                        </div>
                    </div>
                </div>
            </li>

        </ul>
    </div>
  
    <div class="form-actions" style="width: 50%">
        <input class="btn btn-primary" id="btnSubmit" type="button" value="@Resources.Language.Submit" />
        <input class="btn" id="btnBack" type="button" value="Về Trang Danh Sách" />
    </div> 
     
    
}



<script>
    $(document).ready(function () {

        // create Editor from textarea HTML element with default set of tools
        $(".editor").kendoEditor({
           
            encoded:true,
            tools: ["bold", "italic", "underline", "justifyLeft", "justifyCenter", "justifyRight",
                "justifyFull", "insertUnorderedList", "insertOrderedList", "indent", "outdent", "viewHtml"
            ],
           
            
        });
        $("#editor").kendoEditor({

            encoded: true,
            
            tools: ["bold", "italic", "underline", "justifyLeft", "justifyCenter", "justifyRight",
                "justifyFull", "insertUnorderedList", "insertOrderedList", "indent", "outdent", "viewHtml", "insertHtml"
            ],
            insertHtml: [
                   { text: "Chữ ký:", value: "<p>Regards,<br /> By...,<br /></a></p>" }]
        });
        $("#panelbar").kendoPanelBar({
            expandMode: "multiple",
            animation: {
                collapse: {
                    duration: 1000,
                    effects: "fadeOut"
                },
                expand: {
                    duration: 500,
                    effects: "expandVertical fadeIn"
                }

            }
            
        });

        $("#tabstrip").kendoTabStrip({
            animation: {
                open: {
                    effects: ["expandVertical ", "fadeIn"]
                }
                
            }

        });
      
        var validator = $("#panelbar").kendoValidator().data("kendoValidator");

        $('#btnSubmit').click(function () {
            //var editor = $("#editor").data("kendoEditor");
            //var e2 = $("#Travel").data("kendoEditor");
            //var e1 = $("#History").data("kendoEditor");
            //alert(editor.encodedValue());
            //alert(e1.encodedValue() + " ed 2" + e2.encodedValue());
            if (validator.validate()) {
                $('#frmAddCity').submit();
                
               
            } else {
                alert("Oops! There is invalid data in the form.");
            }

        });
    });

</script>



<script>
   
    function htmlEncode(value) {
        if (value) {
            return jQuery('<div />').text(value).html();
        } else {
            return '';
        }
    }
    function htmlDecode(value) {
        if (value) {
            return $('<div />').html(value).text();
        } else {
            return '';
        }
    }
     // logs "<p>foo</p>"
    $('#btnBack').click(function () {
        location.href='@Url.Action("CityManager", "SystemManager")';      
        

    });
</script>





<script>
    $(function () {
        $("#uploadAvatar").kendoUpload({
            localization: {
                remove: "Remove",
                uploadSelectedFiles: "Upload"
            },
            multiple: false,
            async: {
                autoUpload: false,
                saveUrl: '@Url.Action("UploadAvatarCity","File",new {cityId=Model.dlCity.ID})',
                removeUrl: '@Url.Action("RemoveAvatarCity","File")'
            },
            select: function () {
                // The upload button will be created after the event is triggered
                // hence the need for a timeout.
                setTimeout(function () {
                    $(".k-upload-selected").insertBefore($(".k-upload-action"))
                });

            },
            select: onSelect,
            upload: onUpload,
            success: onUploadSuccess
        });
    });
    function onUpload(e) {
        var files = e.files;

        // Check the extension of each file and abort the upload if it is not .jpg ,.png ,.bmp
        $.each(files, function () {
            if ((this.extension == ".jpg") || (this.extension == ".png") || (this.extension == ".bmp")) {
                return true;
            }
            else {
                alert("it is not .jpg ,.png ,.bmp");
                e.preventDefault();
            }
        });
    }
    function onProgress(e) {
        // Array with information about the uploaded files
        var files = e.files;

        console.log(e.percentComplete);
    }
    function onUploadSuccess(e) {
        if (e.operation == "upload") {
            var files = e.response;
            $.each(files, function () {
                var name = files.dataName.toString();
                var id = name.replace('.', '');
                $('#Avatar').val(name);
                $('#imgPhotoAvatar > .row > .span8 > .thumbnails').append("<li class=\"span2\" id=" + id + " ><a class=thumbnail><img src=/Data/Avatar/City/" + name + " alt='' /></a></li>");
                //$('#uploadAvatar').data('kendoUpload').disable();
                e.files[0].name = name;
            });
        }

        if (e.operation == "remove") {
            $.each(e.files, function () {
                $('#Avatar').val('');
                var name = this.name.replace('.', '');
                $('div#imgPhotoAvatar > .row > .span8 > .thumbnails > li').remove('#' + name);
                // $('#uploadAvatar').data('kendoUpload').enable();
            });
        }
    }
    function onSelect(e) {
        var files = e.files;

        // Check the extension of each file and abort the upload if it is not .jpg ,.png ,.bmp
        $.each(files, function () {
            //alert(this.extension);
            if ((this.extension == ".jpg") || (this.extension == ".png") || (this.extension == ".bmp")) {
                return true;
            }
            else {
                alert("it is not .jpg ,.png ,.bmp"); e.preventDefault();
            }
        });
    }
</script>
@section resiseIframe{
    <script>
        zmXCall.resizeParent("dulich", null);
    </script>
}

WebDuLich/WebDuLichDev/Views/City/Detail.cshtml
@model DuLichDLL.Model.DL_City
@{
    ViewBag.Title = Resources.Language.DetailInfo;
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/Content/themes/city.css");
}

<h2>@Resources.Language.DetailInfo @Model.CityName</h2>
<div class="leftpanel" style="width: 40%">
    <ul class="thumbnails">
        <li class="span4">
            <a class="thumbnail cityinfo fancybox.iframe" href="@Url.Action("CityInfoDetail", "City", new {ID= Model.ID, summary=Model.Summary })">
                <img alt="@Model.CityName" src="@DataHelpper.PATH_AVATAR_CITY/@Model.Avatar" title="@Model.CityName - nhấp vào hình để xem thông tin chi tiết" class="avatarcity">
            </a>
        </li>
    </ul>
</div>
<div class="rightpanel" style="width: 60%">
    <p class="drop-cap">
        @Model.Summary
    </p>
    <div class="showcase">       
            @Html.Partial("_BookShow2")
    </div>
</div>
<script>
    $(document).ready(function () {
        $('.cityinfo').fancybox({
            maxWidth: 600,
            fitToView: false,
            width: '537px',
            height: '520px',
            autoSize: false,
            closeClick: false,
            openEffect: 'fadeIn',
            closeEffect: 'none',
            padding: 10,
        });

    });
</script>
<script>
    
    function dosomething() {
        location.href = '@Url.Action("NicePlaceByCity", "Place", new { ID = Model.ID })';
    }
    function dosomething2() {
        location.href = '@Url.Action("RestaurantByCity", "Restaurant", new { ID = Model.ID })';
    }
    function dosomething3() {
        location.href = '@Url.Action("HotelByCity", "Hotel", new { ID = Model.ID })';
    }
</script>