WebDuLich/WebDuLichDev/Controllers/PlaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DuLichDLL.BAL;
using DuLichDLL.Model;
using System.IO;
using DuLichDLL.TOOLS;
using WebDuLichDev.Models;
using WebDuLichDev.WebUtility;
using DuLichDLL.ExceptionType;
using WebDuLichDev.Enum;
using System.Text;
using WebMatrix.WebData;

namespace WebDuLichDev.Controllers
{
    public class PlaceController : Controller
    {
        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(PlaceController).Name);
        string version = "Version " + System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString() + " ";
        //
        // GET: /Place/
        private static List<DL_ImagePlace> listImagePlaceOld = new List<DL_ImagePlace>();

        private static List<vm_NicePlace> nicePlaceBookTemp = new List<vm_NicePlace>();
        [Authorize]
        public ActionResult ListNicePlace()
        {
            try
            {
                vm_Pagination pagination = new vm_Pagination
                {
                    Page = MvcApplication.pageDefault,
                    PageSize = MvcApplication.pageSizeDefault,
                    OrderBy = DL_PlaceColumns.CreatedDate.ToString(),
                    OrderDirection = "DESC",

                };
                long totalRecords = 0;

                DL_PlaceBAL dlPlaceBAL = new DL_PlaceBAL();
                var model = dlPlaceBAL.GetListWithFilter(0, "", "", 0, pagination.Page.Value, pagination.PageSize.Value, pagination.OrderBy, pagination.OrderDirection, out totalRecords);
                common.LoadPagingData(this, pagination.Page ?? MvcApplication.pageDefault, pagination.PageSize ?? MvcApplication.pageSizeDefault, totalRecords);
                ViewData["OrderBy"] = pagination.OrderBy;
                ViewData["OrderDirection"] = pagination.OrderDirection;
                return View(model);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult ListNicePlace(vm_Pagination pagination, vm_Search dataSearch)
        {

            long totalRecords = 0;

            DL_PlaceBAL dlPlaceBAL = new DL_PlaceBAL();
            var model = dlPlaceBAL.GetListWithFilter(dataSearch.cityId ?? 0, dataSearch.placename ?? "", dataSearch.address ?? "", 0, pagination.Page.Value, pagination.PageSize.Value, pagination.OrderBy, pagination.OrderDirection, out totalRecords);
            common.LoadPagingData(this, pagination.Page ?? MvcApplication.pageDefault, pagination.PageSize ?? MvcApplication.pageSizeDefault, totalRecords);
            ViewData["OrderBy"] = pagination.OrderBy;
            ViewData["OrderDirection"] = pagination.OrderDirection;

            return View(model);
        }

        //[Authorize]
        public ActionResult NicePlaceByCity(long ID)
        {
            try
            {
                ViewBag.CityId = ID;

                DL_CityBAL dlCityBal = new DL_CityBAL();
                var city = dlCityBal.GetByID(ID);
                ViewBag.Title = city.CityName;

                vm_Pagination pagination = new vm_Pagination { OrderBy = DL_PlaceColumns.CreatedDate.ToString(), OrderDirection = "DESC" };
                DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
                DL_NicePlaceInfoDetailBAL dlNicePlaceInfoDetailBal = new DL_NicePlaceInfoDetailBAL();
                DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();
                var dlPlace = dlPlaceBal.GetListNicePlaceByCity(ID);
                ViewData["OrderBy"] = pagination.OrderBy;
                ViewData["OrderDirection"] = pagination.OrderDirection;
                var nicePlaceBook = new List<vm_NicePlace>();
                for (int index = 0; index < dlPlace.Count(); index++)
                {
                    var tmp = new vm_NicePlace();
                    tmp.dlPlace = dlPlace[index];
                    tmp.dlNicePlaceInfoDetail = dlNicePlaceInfoDetailBal.GetByPlaceId(dlPlace[index].ID);
                    tmp.listImagePlace = dlImagePlaceBal.GetByDLPlaceID(dlPlace[index].ID);
                    nicePlaceBook.Add(tmp);

                }
                nicePlaceBookTemp = nicePlaceBook;
                return View(nicePlaceBook);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult NicePlace(long ID)
        {
            DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
            DL_NicePlaceInfoDetailBAL dlNicePlaceInfoDetailBal = new DL_NicePlaceInfoDetailBAL();
            DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();

            var nicePlace = new vm_NicePlace();

            //nicePlace = nicePlaceBook.Where(p => p.dlPlace.ID == ID).Single();
            nicePlace.dlPlace = dlPlaceBal.GetByID(ID);
            nicePlace.dlNicePlaceInfoDetail = dlNicePlaceInfoDetailBal.GetByPlaceId(ID);
            nicePlace.listImagePlace = dlImagePlaceBal.GetByDLPlaceID(ID);

            return View(nicePlace);
        }

        public ActionResult ListImagePlace(long placeId)
        {
            DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();
            var model = dlImagePlaceBal.GetByDLPlaceID(placeId);
            return View(model);
        }

        public ActionResult PlaceInfoDetail(long placeId)
        {
            try
            {
                //DL_NicePlaceInfoDetailBAL dlNicePlaceInfoDetail = new DL_NicePlaceInfoDetailBAL();
                //var model = dlNicePlaceInfoDetail.GetByPlaceId(placeId);
                var model = new DL_NicePlaceInfoDetail();
                for (int index = 0; index < nicePlaceBookTemp.Count; index++)
                {
                    if (nicePlaceBookTemp[index].dlNicePlaceInfoDetail.DL_PlaceId == placeId)
                    {
                        model = nicePlaceBookTemp[index].dlNicePlaceInfoDetail;
                    }
                }
                return View(model);
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return RedirectToAction("Error", "Home");
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult PrintBook(long cityId)
        {
           DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();
            if(null != nicePlaceBookTemp && nicePlaceBookTemp.Count !=0)
               for (int index = 0; index < nicePlaceBookTemp.Count; index++)
               {
                   nicePlaceBookTemp[index].listImagePlace = dlImagePlaceBal.GetByDLPlaceID(nicePlaceBookTemp[index].dlPlace.ID);
               }
            var model = nicePlaceBookTemp;
            return View(model);
        }

        [HttpPost]
        public ActionResult Rating(long placeId, int rate)
        {

            try
            {
                long userId = WebSecurity.CurrentUserId; // WebSecurity.CurrentUserId;
                bool success = false;
                string error = "";
                float avg = 0;
                long total = 0;
                //DL_CommentCityBAL dlCommentCityBal = new DL_CommentCityBAL();
                var dlPlaceBal = new DL_PlaceBAL();

                var dlPlace = new DL_Place();
                dlPlace = dlPlaceBal.GetByID(placeId);
                dlPlace.TotalPointRating = dlPlace.TotalPointRating + rate;
                dlPlace.TotalUserRating = dlPlace.TotalUserRating + 1;
                avg = dlPlace.TotalPointRating / dlPlace.TotalUserRating;
                dlPlace.AvgRating = (int)avg;

                if (dlPlaceBal.Update(dlPlace) > 0)
                    success = true;
                //success = db.RegisterProductVote(userId, id, rate);
                total = dlPlace.TotalUserRating;
                ViewBag.AVG = avg;

                return Json(new { success = success, Avg = avg, TotalUser = total});
            }
            catch (BusinessException bx)
            {
                log.Error(bx.Message);
                TempData[PageInfo.Message.ToString()] = bx.Message;
                return null;
            }
            catch (Exception ex)
            {
                //LogBAL.LogEx("BLM_ERR_Common", ex);
                log.Error(ex.Message);
                TempData[PageInfo.Message.ToString()] = "BLM_ERR_Common";
                return null;
            }


        }

        public ActionResult CommentPlace(long placeId, string type)
        {
            ViewBag.placeId = placeId;

WebDuLich/WebDuLichDev/Controllers/RazorPDFController.cs
using DotNetOpenAuth.AspNet;
using DotNetOpenAuth.AspNet.Clients;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using zingme_sdk;
using DuLichDLL.BAL;
using WebDuLichDev.Models;
using iTextSharp.text;
using iTextSharp.text.pdf;
using WebDuLichDev.WebUtility;
using System.Web.Mvc.Html;
using System.Net.Mail;
using iTextSharp.text.html.simpleparser;
using System.Web.UI;
using System.Globalization;
namespace WebDuLichDev.Controllers
{

    public class RazorPDFController : Controller
    {
        private static string placeName="";
        public ActionResult Pdf(long ID)
        {
            DL_PlaceBAL dlPlaceBal = new DL_PlaceBAL();
            DL_NicePlaceInfoDetailBAL dlNicePlaceInfoDetailBal = new DL_NicePlaceInfoDetailBAL();
            DL_ImagePlaceBAL dlImagePlaceBal = new DL_ImagePlaceBAL();

            var tmp = new vm_NicePlace();
            tmp.dlPlace = dlPlaceBal.GetByID(ID);
            tmp.dlNicePlaceInfoDetail = dlNicePlaceInfoDetailBal.GetByPlaceId(tmp.dlPlace.ID);
            tmp.listImagePlace = dlImagePlaceBal.GetByDLPlaceID(tmp.dlPlace.ID);

            placeName = tmp.dlPlace.Name;

            return View(tmp);
          
        }
        public static String RemoveDiacritics(String s)
        {
            String normalizedString = s.Normalize(NormalizationForm.FormD);
            StringBuilder stringBuilder = new StringBuilder();

            for (int i = 0; i < normalizedString.Length; i++)
            {
                Char c = normalizedString[i];
                if (CharUnicodeInfo.GetUnicodeCategory(c) != UnicodeCategory.NonSpacingMark)
                    stringBuilder.Append(c);
            }

            return stringBuilder.ToString();
        }
        
        public ActionResult Pdf_Post(long ID, string urlBase)
        {
            string url = urlBase+"/RazorPDF/pdf/" + ID;
            HttpWebRequest myRequest = (HttpWebRequest)WebRequest.Create(url);
            WebResponse myResponse = myRequest.GetResponse();
            StreamReader sr = new StreamReader(myResponse.GetResponseStream(), System.Text.Encoding.UTF8);
            string result = sr.ReadToEnd();
            sr.Close();
            myResponse.Close();
            var placeName_nonSpecail =RemoveDiacritics(placeName);
            PDFFactory.GeneratePDF(result, placeName_nonSpecail + DateTime.Now.ToShortDateString());
          
            return View();

        }
    }
}

WebDuLich/WebDuLichDev/Controllers/ZingController.cs
using DotNetOpenAuth.AspNet;
using DotNetOpenAuth.AspNet.Clients;
using Newtonsoft.Json;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using WebDuLichDev.WebUtility;
using zingme_sdk;

namespace WebDuLichDev.Controllers
{

    public class ZingController : BaseController
    {
        public ActionResult Invite()
        {
            ZME_Config zme_config = RegisterAuthZing.config();

            ZME_Social zmeSocial = new ZME_Social(zme_config);
            // zmeSocial.invite();
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult PostNoticeRate(int rate, string placeName, long ID)
        {
            if (null == WebDuLichSecurity.AccessTokenZingMe)
                return Json(new { result = false });

            string hostname = ConfigurationManager.AppSettings["Path"].ToString();

            ZME_Config zme_config = RegisterAuthZing.config();
            ZME_Me zmeMe = new ZME_Me(zme_config);
            Hashtable me_info = zmeMe.getInfo(WebDuLichSecurity.AccessTokenZingMe, "id,username");
            ZME_Social zmeSocial = new ZME_Social(zme_config);
            string username = me_info["username"].ToString();
            //string rate= rate.ToString();
            string title = username + " vừa đánh giá cho " + placeName + " được " + rate.ToString() + " điểm trên tổng số 20";
            ZME_Feed zmeFeed = new ZME_Feed(placeName, title, "dia diem", hostname +"Data/Avatar/Place/images.jpg", hostname+"place/niceplace/"+ID, hostname);
            zmeSocial.post(WebDuLichSecurity.AccessTokenZingMe, zmeFeed, false);
            return Json(new { result = true});
        }
    }
    
    
}

WebDuLich/WebDuLichDev/Views/Shared/_ImageSliderLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Scripts.Render("~/Scripts/jquery.min.js")
    @Styles.Render("~/Scripts/Lib/fotorama/fotorama.css")
    @Scripts.Render("~/Scripts/Lib/fotorama/fotorama.js")
    @Scripts.Render("~/Scripts/Lib/fotorama/jquery.js")

</head>
<body>
    @RenderBody()
</body>
</html>

WebDuLich/WebDuLichDev/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Việt Nam Vẻ Đẹp Bất Tận</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.8.2.min.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/base")
    @RenderSection("scripts", required: false)
    <link rel="stylesheet" href="@Url.Content("~/Content/styles/kendo.common.min.css")">
    <link rel="stylesheet" href="@Url.Content("~/Content/styles/kendo.default.min.css")">
    <script src="@Url.Content("~/Scripts/KendoJS/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/KendoJS/kendo.all.min.js")"></script>
    @Scripts.Render("~/Scripts/Lib/FancyBox/source/jquery.fancybox.js")
    @Styles.Render("~/Scripts/Lib/FancyBox/source/jquery.fancybox.css")
    <script type="text/javascript" src="http://static.me.zing.vn/v3/js/zm.xcall-1.01.js"></script>
</head>
<body>
    <div id="header">
        @Html.Partial("p_Header")
    </div>
    <div id="body">
        @*@RenderSection("featured", required: false)*@
        <section>
            @RenderBody()
        </section>
    </div>
    <hr />
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Du Lịch Việt Nam</p>
            </div>
        </div>
    </footer>
    @RenderSection("resiseIframe", false)
</body>
</html>

WebDuLich/WebDuLichDev/Views/Shared/_LayoutFilp.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/themes/20Thing/css/reset.css")
    @Styles.Render("~/Scripts/Lib/bootstrap/css/bootstrap.css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/rating.css")
    @Scripts.Render("~/Scripts/rating.js")
    @Scripts.Render("~/Scripts/jquery-1.8.2.min.js")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/base")
    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    @Styles.Render("~/Content/themes/20Thing/css/main.css")
    @Scripts.Render("~/Scripts/Lib/FancyBox/source/jquery.fancybox.js")
    @Styles.Render("~/Scripts/Lib/FancyBox/source/jquery.fancybox.css")
@*    @Styles.Render("~/Scripts/Lib/notepad/html5notepad.css")
    @Scripts.Render("~/Scripts/Lib/notepad/html5notepad.js")*@
    <link rel="stylesheet" type="text/css" href="~/Scripts/Lib/jRating/jquery/jRating.jquery.css" media="screen" />
    <!-- jQuery files -->
    <script type="text/javascript" src="Scripts/Lib/jRating/jquery/jquery.js"></script>

    <script type="text/javascript">
        document.write('<link rel="stylesheet" type="text/css" media="all" href="css/hideOnLoad.css" />');

        if (window.location.hash.match('\/')) {
            window.location = window.location.protocol + '//' + window.location.hostname + ':' + window.location.port + window.location.hash.slice(1);
        }

        var SERVER_VARIABLES = {
            PAGE: "Page",
            PAGES: "Pages",
            THING: "THING",
            FOREWORD: "FOREWORD",
            LANG: "en-US",
            SITE_VERSION: 49,
            FACEBOOK_MESSAGE: "A fun guidebook from Google on things you've always wanted to know about browsers & the web (but were afraid to ask",
            FACEBOOK_MESSAGE_SINGLE: "A fun fact I learned today from Google's guidebook to browsers and the web.",
            TWITTER_MESSAGE: "A fun guidebook from Google on things you've always wanted to know about browsers & the web:",
            TWITTER_MESSAGE_SINGLE: "A fun fact I learned today from Google's guidebook to browsers and the web: ",
            BUZZ_MESSAGE: "A fun guidebook from Google on things you've always wanted to know about browsers & the web (but were afraid to ask): http://goo.gl/20things",
            BUZZ_MESSAGE_SINGLE: "A fun fact I learned today from Google's guidebook to browsers and the web: ",
            SOLID_BOOK_COLOR: "#5873a0"
        };

        // Set language for use by Google +1 button.
        window.___gcfg = { lang: SERVER_VARIABLES.LANG };
    </script>
</head>
<body class="normal">
    <div id="preloader">
        <div class="contents">
            <canvas class="animation"></canvas>
            <div class="progress">
                <div class="fill"></div>
            </div>
        </div>
    </div>
    <header>
        <nav>
            <ul>
                <li ><a class="back" href="/City/Detail/@ViewBag.CityId">BACK</a></li>
                <li class="table-of-things"><a href="/table-of-things">@Resources.Language.TableOfIndex.ToUpper()</a></li>
                <li class="divider1"></li>
                <li class="about"><a href="#">@Resources.Language.First.ToUpper()</a></li>
                <li class="divider2"></li>
                <li class="credits"><a href="#">@Resources.Language.Credit.ToUpper()</a></li>
                <li class="divider2"></li>
            </ul>
        </nav>

        <div id="language-selector">
            <div id="language-selector-title"><a>VIETNAM (VI)</a></div>
            <div id="language-selector-list">
                <ul>
                    <li><a>ENGLISH (US)</a></li>
                </ul>
            </div>
        </div>

        <!-- Input type="search" is currently too inconsistent across browsers and platforms -->
        <input id="search-field" type="text" value="Search Book">
    </header>
    @RenderBody()
    <footer>
        <span class="curator"><a href="http://www.google.com/chrome?brand=CHJN">Hau Team. ©,2013</a></span>
        <div class="right-side">
            <div class="divider"></div>
            <div class="invite">

                <ul>
                    <li>
                        <div id="zme-root"></div>
                        <script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) { return; }
    js = d.createElement(s);
    js.id = id;
    js.src = "http://static.me.zing.vn/sp/js/all-1.39.js#&appId=663270de6faf4149ac73cb5e77374924&status=true";
    fjs.parentNode.insertBefore(js, fjs);
}
											(document, "script", "zingme-jssdk"));</script>
                        <a class="zme-invite" data-link="http://dulich.azurewebsites.net" data-title="Mời bạn bè" data-type="app"></a>
                    </li>
                </ul>
            </div>
            <div class="divider"></div>
            <div class="sharing">
                <p>@Resources.Language.SHAREBOOK</p>
                <input type="text" class="clipboard-notification" value="" readonly="readonly" />
                <ul>
                    <li class="facebook"><a href="http://www.facebook.com/sharer.php?u=http://20thingsilearned.com&amp;t=20%20Things%20I%20learned%20About%20Browsers%20and%20the%20Web" title="Facebook"></a></li>
                    <li class="twitter"><a href="http://twitter.com/share?original_referer=http://20thingsilearned.com&amp;text=20%20Things%20I%20learned%20About%20Browsers%20and%20the%20Web&amp;url=http://20thingsilearned.com" title="Twitter"></a></li>
                    <li class="gplus"></li>
                    <li class="zingme"><a class="" name="zm_share" type="icon" title="Chia sẻ lên Zing Me"></a>
                        <script src="http://stc.ugc.zdn.vn/link/js/lwb.0.7.js" type="text/javascript"></script>
                    </li>
                    <li class="url"><a href="#"></a></li>
                </ul>
            </div>
            <div class="divider"></div>
            <div class="print">
                <a href="@Url.Action("Pdf", "RazorPDF", new { ID = 24 })" target="_blank" ><span class="icon"></span>PRINT BOOK</a>
            </div>
            <div class="divider"></div>
            <div class="lights-wrapper">
                <div class="lights">
                    <a href="#"><span class="icon">LIGHTS</span></a>
                </div>
            </div>
            <div class="divider"></div>
            <div class="fullscreen-wrapper" style="display: none;">
                <div class="fullscreen">
                    <a href="#"><span class="icon"></span>FULL SCREEN</a>
                </div>
            </div>
        </div>
    </footer>
    <script type="text/javascript">
        $(function () {
            $('.map').fancybox({
                maxWidth: 600,
                fitToView: false,
                width: '550px',
                height: '530px',
                autoSize: false,
                closeClick: false,
                openEffect: 'fadeIn',
                closeEffect: 'none',
                padding: 10,
            });
            
            $('.ptext').fancybox({
                maxWidth: 600,
                fitToView: false,
                width: '537px',
                height: '530px',
                autoSize: false,
                closeClick: false,
                openEffect: 'fadeIn',
                closeEffect: 'none',
                padding: 10,
                //afterClose: function () { location.reload(false); }
            });

            $('.listImage').fancybox({   
                maxWidth: 600,
                fitToView: false,
                width: '537px',
                height: '530px',
                autoSize: false,
                closeClick: false,
                openEffect: 'fadeIn',
                closeEffect: 'none',
                padding: 10,
                //afterClose: function () { location.reload(false); }
            });

            $('.fancyboxCmt').fancybox({
                maxWidth: 600,
                fitToView: false,
                width: '537px',
                height: '530px',
                autoSize: false,
                closeClick: false,
                openEffect: 'fadeIn',
                closeEffect: 'none',
                padding: 10,
                //afterClose: function () { location.reload(false); }
            });
        });
    </script>
    <script src="/Content/themes/20Thing/js/twentythings.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.preloader.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.history.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.locale.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.storage.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.pageflip.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.paperstack.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.illustration.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.navigation.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.cache.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.search.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.chapternav.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.sharing.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.overlay.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.tableofthings.js"></script>
    <script src="/Content/themes/20Thing/js/twentythings.flipintro.js"></script>

    <script type="text/javascript" src="~/Scripts/Lib/jRating/jquery/jRating.jquery.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //$('.test').click(function () { alert('kk') });
            TT.initialize();

            $(".basic").jRating({
                onClick: function (element, rate, idBox,nameBox, widthColorOneStar) {
                    $.ajax({
                        url: '@Url.Action("Rating","Place")',
                        type: "Post",
                        data: { rate: rate, placeId: idBox },
                        dataType: "json",
                        success: function (data) {
                            if (data.success) {

                                $(element).attr('data-average', data.Avg);                                
                                $(element).find('.jRatingAverage').css('width', '0px')
                                $(element).find('.jRatingColor').css('width', widthColorOneStar * data.Avg)

                                $(element).parent().children().last().replaceWith('<p class=\"text\" style=\"float:right\">Current Rate : ' + data.Avg + ' by ' + data.TotalUser + ' people </p>')
                                $.ajax({
                                    url: '@Url.Action("PostNoticeRate","Zing")',
                                    type:"Post",
                                    data:{rate: rate, placeName:nameBox, ID:idBox},
                                    dataType :'json',
                                    success: function (result)
                                    {
                                    }
                                });
                            }
                            else
                                alert("that bai");
                        },
                    });
                }
            });

        });
        
    </script>
</body>
</html>